#!/usr/bin/env bash
# Auto : SAID LAMGHARI

# Fonction pour afficher
# les informations sur un sous-domaine
prdinfo() {
    local domain="$1"
    local subdomain="$2"
    local result=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print}')
    local record_type=$(echo "$result" | awk '{print $4}')
    local destination=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Fonction principale
main() {
    local domain="$1"
    local subdomain="$2"

    # Vérifier si le nom
    # de domaine est fourni
    if [ -z "$domain" ]; then
        echo "Domain name missing."
        exit 1
    fi

    # Liste des sous-domaines
    local subdomains=("www" "lb-01" "web-01" "web-02")

    # Si un sous-domaine est fourni,
    # afficher les informations pour ce sous-domaine
    if [ -n "$subdomain" ]; then
        prdinfo "$domain" "$subdomain"
    else
        # Sinon, afficher les informations
        # pour tous les sous-domaines
        for sub in "${subdomains[@]}"; do
            prdinfo "$domain" "$sub"
        done
    fi
}

# Appeler la fonction principale
# avec les arguments fournis
main "$@"
