#!/usr/bin/env bash
# Bash scrad_ipt that transfers a file
# from our client to a server

# Autor : Said LAMGHARI

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

pth_file="$1"
ad_ip="$2"
usrnme="$3"
pth_ssh_key="$4"

scp -o StrictHostKeyChecking=no -i "$pth_ssh_key" "$pth_file" "$usrnme@$ad_ip":~
