#!/usr/bin/env bash
# Web servers are the piece of software
# generating and serving HTML pages
# let’s install one

# Autor: Said LAMGHARI

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get -y install nginx

# Configure nginx to listen on port 80
sudo sed -i 's/^\(listen\s\+\).*/\180;/' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Create index.html "Hello World!" content
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Print compl.
echo "Nginx web server has been installed and configured. It should be listening on port 80 and returning 'Hello World!'."

# End of script
