#!/usr/bin/env bash
# Web servers are the piece of software
# generating and serving HTML pages
# let’s install one

# Autor: Said LAMGHARI

# Update package lists
sudo apt-get update -y -qq

# Upgrade installed packages
sudo apt-get upgrade -y -qq

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with "Hello World!"
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx
sudo service nginx restart
