#!/usr/bin/env bash
# Web servers are the piece of software
# generating and serving HTML pages
# let’s install one

# Autor: Said LAMGHARI

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/ listen 80;/ listen 80 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart

# Create an index.html file with the content "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html
# end
