#!/usr/bin/env bash
# Configure your Nginx server
# so that /redirect_me is redirecting to another page.

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection
sudo sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart
