#!/usr/bin/env bash
# Web servers are the piece of software
# generating and serving HTML pages
# let’s install one
# configure web-02 to be identical to web-01

# Autor: Said LAMGHARI

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a custom HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure the redirection
sudo sed -i '/listen 80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create a custom 404 HTML file
sudo bash -c 'echo "Ceci n'\''est pas une page" | sudo tee /var/www/html/404.html > /dev/null'

# Configure Nginx to use the custom 404 page
sudo sed -i '/listen 80 default_server;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Define custom header value
HOSTNAME=$(hostname)

# Configure Nginx to add custom header
CONFIG_FILE="/etc/nginx/sites-available/default"
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' $CONFIG_FILE

# Reload Nginx to apply changes
sudo systemctl reload nginx

# Restart Nginx
sudo /etc/init.d/nginx restart

echo "Nginx configured with custom HTTP response header X-Served-By"

# end
