#!/usr/bin/env bash

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Get all processes using the 'ps' command and format the output
ps aux --forest | awk '{printf "%-10s %-4s %-4s %-5s %-5s %-5s %-6s %-5s %-7s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}'
