#!/usr/bin/env bash
# Find the PID of the 7-highlander process
pid=$(pgrep -f "7-highlander")

if [[ -n "$pid" ]]; then
    # Send SIGTERM signal to the process to request termination
    kill "$pid"
    echo "Killed"
else
    echo "Process not found"
fi
