#!/usr/bin/env bash
# This script groups visitors by IP
# HTTP status code, sorts the data based on the number of occurrences
# displays it in the specified format.


awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
