#!/usr/bin/env bash
# This script use while loop for displaying "Best School" 10 times, and on the 9th iteration, it also displays "Hi" on a new line.

cptr=0
while [ $cptr -lt 10 ]; do
    if [ $cptr -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    cptr=$((cptr + 1))
done
