#!/usr/bin/env bash
# This script use while loop for displaying "Best School" 10 times, and on the 9th iteration, it also displays "Hi" on a new line.

counter=0
while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    counter=$((counter + 1))
done
