#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.tmp
echo "127.0.0.2		localhost" > ~/hosts.tmp
echo "8.8.8.8           facebook.com" | sudo tee -a /etc/hosts
cp -f ~/hosts.tmp /etc/hosts
