#!/usr/bin/env bash
# Bash script that displays all active 
# IPv4 IPs on the machine it’s executed on.
# Note that we can see our localhost IP
ifconfig | grep "inet " | tr ":" " " | awk '{print $3}'
