#!/usr/bin/env bash
# Run under the root user, which has the ability to run anything as another user.
# Autor: Said LAMGHARI

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi

sudo -u "$1" whoami
