#!/usr/bin/env bash
# Fix this container so that Nginx
# is running as the nginx user.
# Autor: Said LAMGHARI

# Run Nginx as nginx user and listen on port 8080

# Update Nginx user in nginx.conf
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx port in default site configuration
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
