#!/usr/bin/env bash

# Fix this container so that Nginx
# is running as the nginx user.
# Autor: Said LAMGHARI

# Install nginx if is not installed
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Stop Nginx service
service nginx stop

# Update Nginx config. file
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# for listen on port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start
