#!/usr/bin/env bash
# Fix this container so that Nginx
# is running as the nginx user.
# Autor: Said LAMGHARI

# Run Nginx as nginx user and listen on port 8080

# Update Nginx user in nginx.conf
sed -i 's/#user\s\+www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx port in default site configuration
sed -i 's/listen\s\+80;/listen 8080;/' /etc/nginx/sites-available/default

# Set correct permissions for the Nginx configuration file
chmod 644 /etc/nginx/nginx.conf

# Stop Apache2 if running
systemctl stop apache2

# Start Nginx service as the nginx user
sudo -u nginx systemctl start nginx
