#!/usr/bin/env bash

# Script: 1-create_ssh_key_pair
# Description: This script generates an RSA key pair
# with a specified key name, number of bits, and passphrase.
# Requirements:
#   - The private key will be named 'school'
#   - The key will have 4096 bits
#   - The key will be protected by the passphrase 'betty'
# Autor : SAID LAMGHARI

# Generate RSAkeypair
ssh-keygen -t rsa -b 4096 -C "Generated key for school" -f ~/.ssh/school

# Provide passphrase 'betty'
echo "betty" | ssh-keygen -p -P "" -N ""

# Output smessage
echo "RSA key pair created successfully."
